/* AutoGenerated Code, changes may be overwritten
* INPUT GRAMMAR:
* // Root
* ROOT                := COMMAND
* // Data Types
* NUMBER              := '[0-9]+'
* // Command
* COMMAND             := BASIC_COMMAND
*                      | DATA_COMMAND
*                      | GRAPHICS_2D_COMMAND
*                      | GRAPHICS_3D_COMMAND
*                      | GUI_COMMAND
*                      | IO_COMMAND
*                      | SOUND_COMMAND
* // Basic Commands
* BASIC_COMMAND       := BASIC_DIVERSE_COMMAND
*                      | BASIC_MATHS_COMMAND
*                      | BASIC_STRINGS_COMMAND
*                      | BASIC_TIME_RANDOM_COMMAND
* BASIC_DIVERSE_COMMAND := ''
* BASIC_MATHS_COMMAND   := ''
* BASIC_STRINGS_COMMAND := ''
* BASIC_TIME_RANDOM_COMMAND := ''
* // Data Command
* DATA_COMMAND        := DATA_BANK_COMMAND
*                      | DATA_FILE_SYSTEM_COMMAND
* DATA_BANK_COMMAND     := ''
* DATA_FILE_SYSTEM_COMMAND := ''
* // Graphics 2D Command
* GRAPHICS_2D_COMMAND := GRAPHICS_2D_DISPLAY_COMMAND
*                      | GRAPHICS_2D_GAMMA_COMMAND
*                      | GRAPHICS_2D_GRAPHICS_COMMAND
*                      | GRAPHICS_2D_IMAGES_COMMAND
*                      | GRAPHICS_2D_MOVIES_COMMAND
*                      | GRAPHICS_2D_PIXEL_COMMAND
*                      | GRAPHICS_2D_TEXT_COMMAND
* GRAPHICS_2D_DISPLAY_COMMAND := ''
* GRAPHICS_2D_GAMMA_COMMAND := ''
* GRAPHICS_2D_GRAPHICS_COMMAND := Cls
*                               | ClsColor
*                               | Color
*                               | Line
*                               | Oval
*                               | Rect
* Cls                 := '[cC][lL][sS]\s*' ROOT?
* ClsColor            := '[cC][lL][sS][cC][oO][lL][oO][rR]\s+' red=NUMBER ',\s*' green=NUMBER ',\s*' blue=NUMBER ',\s*' ROOT?
* Color               := '[cC][oO][lL][oO][rR]\s+' red=NUMBER ',\s*' green=NUMBER ',\s*' blue=NUMBER ',\s*' ROOT?
* Line                := '[lL][iI][nN][eE]\s+' beginX=NUMBER ',\s*' beginY=NUMBER ',\s*' endX=NUMBER ',\s*' endY=NUMBER ',\s*' ROOT?
* Oval                := '[oO][vV][aA][lL]\s+' x=NUMBER ',\s*' y=NUMBER ',\s?' width=NUMBER ',\s*' height=NUMBER ',\s*' ROOT?  // TODO: optional 5th parameter
* Rect                := '[rR][eE][cC][tT]\s+' x=NUMBER ',\s*' y=NUMBER ',\s*' width=NUMBER ',\s*' height=NUMBER ',\s*' ROOT?  // TODO: optional 5th parameter
* GRAPHICS_2D_IMAGES_COMMAND := ''
* GRAPHICS_2D_MOVIES_COMMAND := ''
* GRAPHICS_2D_PIXEL_COMMAND := ''
* GRAPHICS_2D_TEXT_COMMAND := ''
* // Graphics 3D Command
* GRAPHICS_3D_COMMAND := GRAPHICS_3D_ANIMATIONS_COMMAND
*                      | GRAPHICS_3D_BRUSHES_COMMAND
*                      | GRAPHICS_3D_CAMERA_COMMAND
*                      | GRAPHICS_3D_COLLISIONS_COMMAND
*                      | GRAPHICS_3D_CONTROLS_COMMAND
*                      | GRAPHICS_3D_COORDINATES_COMMAND
*                      | GRAPHICS_3D_DIVERSE_COMMAND
*                      | GRAPHICS_3D_LIGHT_SHADOW_COMMAND
*                      | GRAPHICS_3D_MESHES_COMMAND
*                      | GRAPHICS_3D_PICKING_COMMAND
*                      | GRAPHICS_3D_SCENE_COMMAND
*                      | GRAPHICS_3D_SCENERY_COMMAND
*                      | GRAPHICS_3D_SCREEN_COMMAND
*                      | GRAPHICS_3D_SPRITES_COMMAND
*                      | GRAPHICS_3D_STATUS_COMMAND
*                      | GRAPHICS_3D_SURFACES_COMMAND
*                      | GRAPHICS_3D_TERRAIN_COMMAND
*                      | GRAPHICS_3D_TEXTURES_COMMAND
* GRAPHICS_3D_ANIMATIONS_COMMAND := ''
* GRAPHICS_3D_BRUSHES_COMMAND := ''
* GRAPHICS_3D_CAMERA_COMMAND := ''
* GRAPHICS_3D_COLLISIONS_COMMAND := ''
* GRAPHICS_3D_CONTROLS_COMMAND := ''
* GRAPHICS_3D_COORDINATES_COMMAND := ''
* GRAPHICS_3D_DIVERSE_COMMAND := ''
* GRAPHICS_3D_LIGHT_SHADOW_COMMAND := ''
* GRAPHICS_3D_MESHES_COMMAND := ''
* GRAPHICS_3D_PICKING_COMMAND := ''
* GRAPHICS_3D_SCENE_COMMAND := ''
* GRAPHICS_3D_SCENERY_COMMAND := ''
* GRAPHICS_3D_SCREEN_COMMAND := ''
* GRAPHICS_3D_SPRITES_COMMAND := ''
* GRAPHICS_3D_STATUS_COMMAND := ''
* GRAPHICS_3D_SURFACES_COMMAND := ''
* GRAPHICS_3D_TERRAIN_COMMAND := ''
* GRAPHICS_3D_TEXTURES_COMMAND := ''
* // GUI Command
* GUI_COMMAND         := GUI_BUTTON_COMMAND
*                      | GUI_CANVAS_COMMAND
*                      | GUI_DESKTOP_COMMAND
*                      | GUI_DIVERSE_COMMAND
*                      | GUI_EVENT_COMMAND
*                      | GUI_GADGET_COMMAND
*                      | GUI_HTML_COMMAND
*                      | GUI_ICON_STRIP_COMMAND
*                      | GUI_LIST_TABBER_COMMAND
*                      | GUI_MENU_COMMAND
*                      | GUI_PANEL_COMMAND
*                      | GUI_PROGRESS_BAR_COMMAND
*                      | GUI_REQUEST_COMMAND
*                      | GUI_SLIDER_COMMAND
*                      | GUI_TEXT_AREA_COMMAND
*                      | GUI_TEXT_FIELD_COMMAND
*                      | GUI_TOOLBAR_COMMAND
*                      | GUI_TREE_VIEW_COMMAND
*                      | GUI_WINDOW_COMMAND
* GUI_BUTTON_COMMAND := ''
* GUI_CANVAS_COMMAND := ''
* GUI_DESKTOP_COMMAND := ''
* GUI_DIVERSE_COMMAND := ''
* GUI_EVENT_COMMAND := ''
* GUI_GADGET_COMMAND := ''
* GUI_HTML_COMMAND := ''
* GUI_ICON_STRIP_COMMAND := ''
* GUI_LIST_TABBER_COMMAND := ''
* GUI_MENU_COMMAND := ''
* GUI_PANEL_COMMAND := ''
* GUI_PROGRESS_BAR_COMMAND := ''
* GUI_REQUEST_COMMAND := ''
* GUI_SLIDER_COMMAND := ''
* GUI_TEXT_AREA_COMMAND := ''
* GUI_TEXT_FIELD_COMMAND := ''
* GUI_TOOLBAR_COMMAND := ''
* GUI_TREE_VIEW_COMMAND := ''
* GUI_WINDOW_COMMAND := ''
* // IO Command
* IO_COMMAND          := IO_GAMEPAD_COMMAND
*                      | IO_KEYBOARD_COMMAND
*                      | IO_MOUSE_COMMAND
* IO_GAMEPAD_COMMAND := ''
* IO_KEYBOARD_COMMAND := ''
* IO_MOUSE_COMMAND := ''
* // Sound Command
* SOUND_COMMAND       := SOUND_3D_COMMAND
*                      | SOUND_CHANNELS_COMMAND
*                      | SOUND_MUSIC_SAMPLES_COMMAND
* SOUND_3D_COMMAND := ''
* SOUND_CHANNELS_COMMAND := ''
* SOUND_MUSIC_SAMPLES_COMMAND := ''
*/
type Nullable<T> = T | null;
type $$RuleType<T> = (log?: (msg: string) => void) => Nullable<T>;
export interface ContextRecorder {
    record(pos: PosInfo, depth: number, result: any, negating: boolean, extraInfo: string[]): void;
}
interface ASTNodeIntf {
    kind: ASTKinds;
}
export enum ASTKinds {
    ROOT = "ROOT",
    NUMBER = "NUMBER",
    COMMAND_1 = "COMMAND_1",
    COMMAND_2 = "COMMAND_2",
    COMMAND_3 = "COMMAND_3",
    COMMAND_4 = "COMMAND_4",
    COMMAND_5 = "COMMAND_5",
    COMMAND_6 = "COMMAND_6",
    COMMAND_7 = "COMMAND_7",
    BASIC_COMMAND_1 = "BASIC_COMMAND_1",
    BASIC_COMMAND_2 = "BASIC_COMMAND_2",
    BASIC_COMMAND_3 = "BASIC_COMMAND_3",
    BASIC_COMMAND_4 = "BASIC_COMMAND_4",
    BASIC_DIVERSE_COMMAND = "BASIC_DIVERSE_COMMAND",
    BASIC_MATHS_COMMAND = "BASIC_MATHS_COMMAND",
    BASIC_STRINGS_COMMAND = "BASIC_STRINGS_COMMAND",
    BASIC_TIME_RANDOM_COMMAND = "BASIC_TIME_RANDOM_COMMAND",
    DATA_COMMAND_1 = "DATA_COMMAND_1",
    DATA_COMMAND_2 = "DATA_COMMAND_2",
    DATA_BANK_COMMAND = "DATA_BANK_COMMAND",
    DATA_FILE_SYSTEM_COMMAND = "DATA_FILE_SYSTEM_COMMAND",
    GRAPHICS_2D_COMMAND_1 = "GRAPHICS_2D_COMMAND_1",
    GRAPHICS_2D_COMMAND_2 = "GRAPHICS_2D_COMMAND_2",
    GRAPHICS_2D_COMMAND_3 = "GRAPHICS_2D_COMMAND_3",
    GRAPHICS_2D_COMMAND_4 = "GRAPHICS_2D_COMMAND_4",
    GRAPHICS_2D_COMMAND_5 = "GRAPHICS_2D_COMMAND_5",
    GRAPHICS_2D_COMMAND_6 = "GRAPHICS_2D_COMMAND_6",
    GRAPHICS_2D_COMMAND_7 = "GRAPHICS_2D_COMMAND_7",
    GRAPHICS_2D_DISPLAY_COMMAND = "GRAPHICS_2D_DISPLAY_COMMAND",
    GRAPHICS_2D_GAMMA_COMMAND = "GRAPHICS_2D_GAMMA_COMMAND",
    GRAPHICS_2D_GRAPHICS_COMMAND_1 = "GRAPHICS_2D_GRAPHICS_COMMAND_1",
    GRAPHICS_2D_GRAPHICS_COMMAND_2 = "GRAPHICS_2D_GRAPHICS_COMMAND_2",
    GRAPHICS_2D_GRAPHICS_COMMAND_3 = "GRAPHICS_2D_GRAPHICS_COMMAND_3",
    GRAPHICS_2D_GRAPHICS_COMMAND_4 = "GRAPHICS_2D_GRAPHICS_COMMAND_4",
    GRAPHICS_2D_GRAPHICS_COMMAND_5 = "GRAPHICS_2D_GRAPHICS_COMMAND_5",
    GRAPHICS_2D_GRAPHICS_COMMAND_6 = "GRAPHICS_2D_GRAPHICS_COMMAND_6",
    Cls = "Cls",
    ClsColor = "ClsColor",
    Color = "Color",
    Line = "Line",
    Oval = "Oval",
    Rect = "Rect",
    GRAPHICS_2D_IMAGES_COMMAND = "GRAPHICS_2D_IMAGES_COMMAND",
    GRAPHICS_2D_MOVIES_COMMAND = "GRAPHICS_2D_MOVIES_COMMAND",
    GRAPHICS_2D_PIXEL_COMMAND = "GRAPHICS_2D_PIXEL_COMMAND",
    GRAPHICS_2D_TEXT_COMMAND = "GRAPHICS_2D_TEXT_COMMAND",
    GRAPHICS_3D_COMMAND_1 = "GRAPHICS_3D_COMMAND_1",
    GRAPHICS_3D_COMMAND_2 = "GRAPHICS_3D_COMMAND_2",
    GRAPHICS_3D_COMMAND_3 = "GRAPHICS_3D_COMMAND_3",
    GRAPHICS_3D_COMMAND_4 = "GRAPHICS_3D_COMMAND_4",
    GRAPHICS_3D_COMMAND_5 = "GRAPHICS_3D_COMMAND_5",
    GRAPHICS_3D_COMMAND_6 = "GRAPHICS_3D_COMMAND_6",
    GRAPHICS_3D_COMMAND_7 = "GRAPHICS_3D_COMMAND_7",
    GRAPHICS_3D_COMMAND_8 = "GRAPHICS_3D_COMMAND_8",
    GRAPHICS_3D_COMMAND_9 = "GRAPHICS_3D_COMMAND_9",
    GRAPHICS_3D_COMMAND_10 = "GRAPHICS_3D_COMMAND_10",
    GRAPHICS_3D_COMMAND_11 = "GRAPHICS_3D_COMMAND_11",
    GRAPHICS_3D_COMMAND_12 = "GRAPHICS_3D_COMMAND_12",
    GRAPHICS_3D_COMMAND_13 = "GRAPHICS_3D_COMMAND_13",
    GRAPHICS_3D_COMMAND_14 = "GRAPHICS_3D_COMMAND_14",
    GRAPHICS_3D_COMMAND_15 = "GRAPHICS_3D_COMMAND_15",
    GRAPHICS_3D_COMMAND_16 = "GRAPHICS_3D_COMMAND_16",
    GRAPHICS_3D_COMMAND_17 = "GRAPHICS_3D_COMMAND_17",
    GRAPHICS_3D_COMMAND_18 = "GRAPHICS_3D_COMMAND_18",
    GRAPHICS_3D_ANIMATIONS_COMMAND = "GRAPHICS_3D_ANIMATIONS_COMMAND",
    GRAPHICS_3D_BRUSHES_COMMAND = "GRAPHICS_3D_BRUSHES_COMMAND",
    GRAPHICS_3D_CAMERA_COMMAND = "GRAPHICS_3D_CAMERA_COMMAND",
    GRAPHICS_3D_COLLISIONS_COMMAND = "GRAPHICS_3D_COLLISIONS_COMMAND",
    GRAPHICS_3D_CONTROLS_COMMAND = "GRAPHICS_3D_CONTROLS_COMMAND",
    GRAPHICS_3D_COORDINATES_COMMAND = "GRAPHICS_3D_COORDINATES_COMMAND",
    GRAPHICS_3D_DIVERSE_COMMAND = "GRAPHICS_3D_DIVERSE_COMMAND",
    GRAPHICS_3D_LIGHT_SHADOW_COMMAND = "GRAPHICS_3D_LIGHT_SHADOW_COMMAND",
    GRAPHICS_3D_MESHES_COMMAND = "GRAPHICS_3D_MESHES_COMMAND",
    GRAPHICS_3D_PICKING_COMMAND = "GRAPHICS_3D_PICKING_COMMAND",
    GRAPHICS_3D_SCENE_COMMAND = "GRAPHICS_3D_SCENE_COMMAND",
    GRAPHICS_3D_SCENERY_COMMAND = "GRAPHICS_3D_SCENERY_COMMAND",
    GRAPHICS_3D_SCREEN_COMMAND = "GRAPHICS_3D_SCREEN_COMMAND",
    GRAPHICS_3D_SPRITES_COMMAND = "GRAPHICS_3D_SPRITES_COMMAND",
    GRAPHICS_3D_STATUS_COMMAND = "GRAPHICS_3D_STATUS_COMMAND",
    GRAPHICS_3D_SURFACES_COMMAND = "GRAPHICS_3D_SURFACES_COMMAND",
    GRAPHICS_3D_TERRAIN_COMMAND = "GRAPHICS_3D_TERRAIN_COMMAND",
    GRAPHICS_3D_TEXTURES_COMMAND = "GRAPHICS_3D_TEXTURES_COMMAND",
    GUI_COMMAND_1 = "GUI_COMMAND_1",
    GUI_COMMAND_2 = "GUI_COMMAND_2",
    GUI_COMMAND_3 = "GUI_COMMAND_3",
    GUI_COMMAND_4 = "GUI_COMMAND_4",
    GUI_COMMAND_5 = "GUI_COMMAND_5",
    GUI_COMMAND_6 = "GUI_COMMAND_6",
    GUI_COMMAND_7 = "GUI_COMMAND_7",
    GUI_COMMAND_8 = "GUI_COMMAND_8",
    GUI_COMMAND_9 = "GUI_COMMAND_9",
    GUI_COMMAND_10 = "GUI_COMMAND_10",
    GUI_COMMAND_11 = "GUI_COMMAND_11",
    GUI_COMMAND_12 = "GUI_COMMAND_12",
    GUI_COMMAND_13 = "GUI_COMMAND_13",
    GUI_COMMAND_14 = "GUI_COMMAND_14",
    GUI_COMMAND_15 = "GUI_COMMAND_15",
    GUI_COMMAND_16 = "GUI_COMMAND_16",
    GUI_COMMAND_17 = "GUI_COMMAND_17",
    GUI_COMMAND_18 = "GUI_COMMAND_18",
    GUI_COMMAND_19 = "GUI_COMMAND_19",
    GUI_BUTTON_COMMAND = "GUI_BUTTON_COMMAND",
    GUI_CANVAS_COMMAND = "GUI_CANVAS_COMMAND",
    GUI_DESKTOP_COMMAND = "GUI_DESKTOP_COMMAND",
    GUI_DIVERSE_COMMAND = "GUI_DIVERSE_COMMAND",
    GUI_EVENT_COMMAND = "GUI_EVENT_COMMAND",
    GUI_GADGET_COMMAND = "GUI_GADGET_COMMAND",
    GUI_HTML_COMMAND = "GUI_HTML_COMMAND",
    GUI_ICON_STRIP_COMMAND = "GUI_ICON_STRIP_COMMAND",
    GUI_LIST_TABBER_COMMAND = "GUI_LIST_TABBER_COMMAND",
    GUI_MENU_COMMAND = "GUI_MENU_COMMAND",
    GUI_PANEL_COMMAND = "GUI_PANEL_COMMAND",
    GUI_PROGRESS_BAR_COMMAND = "GUI_PROGRESS_BAR_COMMAND",
    GUI_REQUEST_COMMAND = "GUI_REQUEST_COMMAND",
    GUI_SLIDER_COMMAND = "GUI_SLIDER_COMMAND",
    GUI_TEXT_AREA_COMMAND = "GUI_TEXT_AREA_COMMAND",
    GUI_TEXT_FIELD_COMMAND = "GUI_TEXT_FIELD_COMMAND",
    GUI_TOOLBAR_COMMAND = "GUI_TOOLBAR_COMMAND",
    GUI_TREE_VIEW_COMMAND = "GUI_TREE_VIEW_COMMAND",
    GUI_WINDOW_COMMAND = "GUI_WINDOW_COMMAND",
    IO_COMMAND_1 = "IO_COMMAND_1",
    IO_COMMAND_2 = "IO_COMMAND_2",
    IO_COMMAND_3 = "IO_COMMAND_3",
    IO_GAMEPAD_COMMAND = "IO_GAMEPAD_COMMAND",
    IO_KEYBOARD_COMMAND = "IO_KEYBOARD_COMMAND",
    IO_MOUSE_COMMAND = "IO_MOUSE_COMMAND",
    SOUND_COMMAND_1 = "SOUND_COMMAND_1",
    SOUND_COMMAND_2 = "SOUND_COMMAND_2",
    SOUND_COMMAND_3 = "SOUND_COMMAND_3",
    SOUND_3D_COMMAND = "SOUND_3D_COMMAND",
    SOUND_CHANNELS_COMMAND = "SOUND_CHANNELS_COMMAND",
    SOUND_MUSIC_SAMPLES_COMMAND = "SOUND_MUSIC_SAMPLES_COMMAND",
}
export type ROOT = COMMAND;
export type NUMBER = string;
export type COMMAND = COMMAND_1 | COMMAND_2 | COMMAND_3 | COMMAND_4 | COMMAND_5 | COMMAND_6 | COMMAND_7;
export type COMMAND_1 = BASIC_COMMAND;
export type COMMAND_2 = DATA_COMMAND;
export type COMMAND_3 = GRAPHICS_2D_COMMAND;
export type COMMAND_4 = GRAPHICS_3D_COMMAND;
export type COMMAND_5 = GUI_COMMAND;
export type COMMAND_6 = IO_COMMAND;
export type COMMAND_7 = SOUND_COMMAND;
export type BASIC_COMMAND = BASIC_COMMAND_1 | BASIC_COMMAND_2 | BASIC_COMMAND_3 | BASIC_COMMAND_4;
export type BASIC_COMMAND_1 = BASIC_DIVERSE_COMMAND;
export type BASIC_COMMAND_2 = BASIC_MATHS_COMMAND;
export type BASIC_COMMAND_3 = BASIC_STRINGS_COMMAND;
export type BASIC_COMMAND_4 = BASIC_TIME_RANDOM_COMMAND;
export type BASIC_DIVERSE_COMMAND = string;
export type BASIC_MATHS_COMMAND = string;
export type BASIC_STRINGS_COMMAND = string;
export type BASIC_TIME_RANDOM_COMMAND = string;
export type DATA_COMMAND = DATA_COMMAND_1 | DATA_COMMAND_2;
export type DATA_COMMAND_1 = DATA_BANK_COMMAND;
export type DATA_COMMAND_2 = DATA_FILE_SYSTEM_COMMAND;
export type DATA_BANK_COMMAND = string;
export type DATA_FILE_SYSTEM_COMMAND = string;
export type GRAPHICS_2D_COMMAND = GRAPHICS_2D_COMMAND_1 | GRAPHICS_2D_COMMAND_2 | GRAPHICS_2D_COMMAND_3 | GRAPHICS_2D_COMMAND_4 | GRAPHICS_2D_COMMAND_5 | GRAPHICS_2D_COMMAND_6 | GRAPHICS_2D_COMMAND_7;
export type GRAPHICS_2D_COMMAND_1 = GRAPHICS_2D_DISPLAY_COMMAND;
export type GRAPHICS_2D_COMMAND_2 = GRAPHICS_2D_GAMMA_COMMAND;
export type GRAPHICS_2D_COMMAND_3 = GRAPHICS_2D_GRAPHICS_COMMAND;
export type GRAPHICS_2D_COMMAND_4 = GRAPHICS_2D_IMAGES_COMMAND;
export type GRAPHICS_2D_COMMAND_5 = GRAPHICS_2D_MOVIES_COMMAND;
export type GRAPHICS_2D_COMMAND_6 = GRAPHICS_2D_PIXEL_COMMAND;
export type GRAPHICS_2D_COMMAND_7 = GRAPHICS_2D_TEXT_COMMAND;
export type GRAPHICS_2D_DISPLAY_COMMAND = string;
export type GRAPHICS_2D_GAMMA_COMMAND = string;
export type GRAPHICS_2D_GRAPHICS_COMMAND = GRAPHICS_2D_GRAPHICS_COMMAND_1 | GRAPHICS_2D_GRAPHICS_COMMAND_2 | GRAPHICS_2D_GRAPHICS_COMMAND_3 | GRAPHICS_2D_GRAPHICS_COMMAND_4 | GRAPHICS_2D_GRAPHICS_COMMAND_5 | GRAPHICS_2D_GRAPHICS_COMMAND_6;
export type GRAPHICS_2D_GRAPHICS_COMMAND_1 = Cls;
export type GRAPHICS_2D_GRAPHICS_COMMAND_2 = ClsColor;
export type GRAPHICS_2D_GRAPHICS_COMMAND_3 = Color;
export type GRAPHICS_2D_GRAPHICS_COMMAND_4 = Line;
export type GRAPHICS_2D_GRAPHICS_COMMAND_5 = Oval;
export type GRAPHICS_2D_GRAPHICS_COMMAND_6 = Rect;
export interface Cls {
    kind: ASTKinds.Cls;
}
export interface ClsColor {
    kind: ASTKinds.ClsColor;
    red: NUMBER;
    green: NUMBER;
    blue: NUMBER;
}
export interface Color {
    kind: ASTKinds.Color;
    red: NUMBER;
    green: NUMBER;
    blue: NUMBER;
}
export interface Line {
    kind: ASTKinds.Line;
    beginX: NUMBER;
    beginY: NUMBER;
    endX: NUMBER;
    endY: NUMBER;
}
export interface Oval {
    kind: ASTKinds.Oval;
    x: NUMBER;
    y: NUMBER;
    width: NUMBER;
    height: NUMBER;
}
export interface Rect {
    kind: ASTKinds.Rect;
    x: NUMBER;
    y: NUMBER;
    width: NUMBER;
    height: NUMBER;
}
export type GRAPHICS_2D_IMAGES_COMMAND = string;
export type GRAPHICS_2D_MOVIES_COMMAND = string;
export type GRAPHICS_2D_PIXEL_COMMAND = string;
export type GRAPHICS_2D_TEXT_COMMAND = string;
export type GRAPHICS_3D_COMMAND = GRAPHICS_3D_COMMAND_1 | GRAPHICS_3D_COMMAND_2 | GRAPHICS_3D_COMMAND_3 | GRAPHICS_3D_COMMAND_4 | GRAPHICS_3D_COMMAND_5 | GRAPHICS_3D_COMMAND_6 | GRAPHICS_3D_COMMAND_7 | GRAPHICS_3D_COMMAND_8 | GRAPHICS_3D_COMMAND_9 | GRAPHICS_3D_COMMAND_10 | GRAPHICS_3D_COMMAND_11 | GRAPHICS_3D_COMMAND_12 | GRAPHICS_3D_COMMAND_13 | GRAPHICS_3D_COMMAND_14 | GRAPHICS_3D_COMMAND_15 | GRAPHICS_3D_COMMAND_16 | GRAPHICS_3D_COMMAND_17 | GRAPHICS_3D_COMMAND_18;
export type GRAPHICS_3D_COMMAND_1 = GRAPHICS_3D_ANIMATIONS_COMMAND;
export type GRAPHICS_3D_COMMAND_2 = GRAPHICS_3D_BRUSHES_COMMAND;
export type GRAPHICS_3D_COMMAND_3 = GRAPHICS_3D_CAMERA_COMMAND;
export type GRAPHICS_3D_COMMAND_4 = GRAPHICS_3D_COLLISIONS_COMMAND;
export type GRAPHICS_3D_COMMAND_5 = GRAPHICS_3D_CONTROLS_COMMAND;
export type GRAPHICS_3D_COMMAND_6 = GRAPHICS_3D_COORDINATES_COMMAND;
export type GRAPHICS_3D_COMMAND_7 = GRAPHICS_3D_DIVERSE_COMMAND;
export type GRAPHICS_3D_COMMAND_8 = GRAPHICS_3D_LIGHT_SHADOW_COMMAND;
export type GRAPHICS_3D_COMMAND_9 = GRAPHICS_3D_MESHES_COMMAND;
export type GRAPHICS_3D_COMMAND_10 = GRAPHICS_3D_PICKING_COMMAND;
export type GRAPHICS_3D_COMMAND_11 = GRAPHICS_3D_SCENE_COMMAND;
export type GRAPHICS_3D_COMMAND_12 = GRAPHICS_3D_SCENERY_COMMAND;
export type GRAPHICS_3D_COMMAND_13 = GRAPHICS_3D_SCREEN_COMMAND;
export type GRAPHICS_3D_COMMAND_14 = GRAPHICS_3D_SPRITES_COMMAND;
export type GRAPHICS_3D_COMMAND_15 = GRAPHICS_3D_STATUS_COMMAND;
export type GRAPHICS_3D_COMMAND_16 = GRAPHICS_3D_SURFACES_COMMAND;
export type GRAPHICS_3D_COMMAND_17 = GRAPHICS_3D_TERRAIN_COMMAND;
export type GRAPHICS_3D_COMMAND_18 = GRAPHICS_3D_TEXTURES_COMMAND;
export type GRAPHICS_3D_ANIMATIONS_COMMAND = string;
export type GRAPHICS_3D_BRUSHES_COMMAND = string;
export type GRAPHICS_3D_CAMERA_COMMAND = string;
export type GRAPHICS_3D_COLLISIONS_COMMAND = string;
export type GRAPHICS_3D_CONTROLS_COMMAND = string;
export type GRAPHICS_3D_COORDINATES_COMMAND = string;
export type GRAPHICS_3D_DIVERSE_COMMAND = string;
export type GRAPHICS_3D_LIGHT_SHADOW_COMMAND = string;
export type GRAPHICS_3D_MESHES_COMMAND = string;
export type GRAPHICS_3D_PICKING_COMMAND = string;
export type GRAPHICS_3D_SCENE_COMMAND = string;
export type GRAPHICS_3D_SCENERY_COMMAND = string;
export type GRAPHICS_3D_SCREEN_COMMAND = string;
export type GRAPHICS_3D_SPRITES_COMMAND = string;
export type GRAPHICS_3D_STATUS_COMMAND = string;
export type GRAPHICS_3D_SURFACES_COMMAND = string;
export type GRAPHICS_3D_TERRAIN_COMMAND = string;
export type GRAPHICS_3D_TEXTURES_COMMAND = string;
export type GUI_COMMAND = GUI_COMMAND_1 | GUI_COMMAND_2 | GUI_COMMAND_3 | GUI_COMMAND_4 | GUI_COMMAND_5 | GUI_COMMAND_6 | GUI_COMMAND_7 | GUI_COMMAND_8 | GUI_COMMAND_9 | GUI_COMMAND_10 | GUI_COMMAND_11 | GUI_COMMAND_12 | GUI_COMMAND_13 | GUI_COMMAND_14 | GUI_COMMAND_15 | GUI_COMMAND_16 | GUI_COMMAND_17 | GUI_COMMAND_18 | GUI_COMMAND_19;
export type GUI_COMMAND_1 = GUI_BUTTON_COMMAND;
export type GUI_COMMAND_2 = GUI_CANVAS_COMMAND;
export type GUI_COMMAND_3 = GUI_DESKTOP_COMMAND;
export type GUI_COMMAND_4 = GUI_DIVERSE_COMMAND;
export type GUI_COMMAND_5 = GUI_EVENT_COMMAND;
export type GUI_COMMAND_6 = GUI_GADGET_COMMAND;
export type GUI_COMMAND_7 = GUI_HTML_COMMAND;
export type GUI_COMMAND_8 = GUI_ICON_STRIP_COMMAND;
export type GUI_COMMAND_9 = GUI_LIST_TABBER_COMMAND;
export type GUI_COMMAND_10 = GUI_MENU_COMMAND;
export type GUI_COMMAND_11 = GUI_PANEL_COMMAND;
export type GUI_COMMAND_12 = GUI_PROGRESS_BAR_COMMAND;
export type GUI_COMMAND_13 = GUI_REQUEST_COMMAND;
export type GUI_COMMAND_14 = GUI_SLIDER_COMMAND;
export type GUI_COMMAND_15 = GUI_TEXT_AREA_COMMAND;
export type GUI_COMMAND_16 = GUI_TEXT_FIELD_COMMAND;
export type GUI_COMMAND_17 = GUI_TOOLBAR_COMMAND;
export type GUI_COMMAND_18 = GUI_TREE_VIEW_COMMAND;
export type GUI_COMMAND_19 = GUI_WINDOW_COMMAND;
export type GUI_BUTTON_COMMAND = string;
export type GUI_CANVAS_COMMAND = string;
export type GUI_DESKTOP_COMMAND = string;
export type GUI_DIVERSE_COMMAND = string;
export type GUI_EVENT_COMMAND = string;
export type GUI_GADGET_COMMAND = string;
export type GUI_HTML_COMMAND = string;
export type GUI_ICON_STRIP_COMMAND = string;
export type GUI_LIST_TABBER_COMMAND = string;
export type GUI_MENU_COMMAND = string;
export type GUI_PANEL_COMMAND = string;
export type GUI_PROGRESS_BAR_COMMAND = string;
export type GUI_REQUEST_COMMAND = string;
export type GUI_SLIDER_COMMAND = string;
export type GUI_TEXT_AREA_COMMAND = string;
export type GUI_TEXT_FIELD_COMMAND = string;
export type GUI_TOOLBAR_COMMAND = string;
export type GUI_TREE_VIEW_COMMAND = string;
export type GUI_WINDOW_COMMAND = string;
export type IO_COMMAND = IO_COMMAND_1 | IO_COMMAND_2 | IO_COMMAND_3;
export type IO_COMMAND_1 = IO_GAMEPAD_COMMAND;
export type IO_COMMAND_2 = IO_KEYBOARD_COMMAND;
export type IO_COMMAND_3 = IO_MOUSE_COMMAND;
export type IO_GAMEPAD_COMMAND = string;
export type IO_KEYBOARD_COMMAND = string;
export type IO_MOUSE_COMMAND = string;
export type SOUND_COMMAND = SOUND_COMMAND_1 | SOUND_COMMAND_2 | SOUND_COMMAND_3;
export type SOUND_COMMAND_1 = SOUND_3D_COMMAND;
export type SOUND_COMMAND_2 = SOUND_CHANNELS_COMMAND;
export type SOUND_COMMAND_3 = SOUND_MUSIC_SAMPLES_COMMAND;
export type SOUND_3D_COMMAND = string;
export type SOUND_CHANNELS_COMMAND = string;
export type SOUND_MUSIC_SAMPLES_COMMAND = string;
export class Parser {
    private readonly input: string;
    private pos: PosInfo;
    private negating: boolean = false;
    constructor(input: string) {
        this.pos = {overallPos: 0, line: 1, offset: 0};
        this.input = input;
    }
    public reset(pos: PosInfo) {
        this.pos = pos;
    }
    public finished(): boolean {
        return this.pos.overallPos === this.input.length;
    }
    public matchROOT($$dpth: number, $$cr?: ContextRecorder): Nullable<ROOT> {
        return this.matchCOMMAND($$dpth + 1, $$cr);
    }
    public matchNUMBER($$dpth: number, $$cr?: ContextRecorder): Nullable<NUMBER> {
        return this.regexAccept(String.raw`(?:[0-9]+)`, $$dpth + 1, $$cr);
    }
    public matchCOMMAND($$dpth: number, $$cr?: ContextRecorder): Nullable<COMMAND> {
        return this.choice<COMMAND>([
            () => this.matchCOMMAND_1($$dpth + 1, $$cr),
            () => this.matchCOMMAND_2($$dpth + 1, $$cr),
            () => this.matchCOMMAND_3($$dpth + 1, $$cr),
            () => this.matchCOMMAND_4($$dpth + 1, $$cr),
            () => this.matchCOMMAND_5($$dpth + 1, $$cr),
            () => this.matchCOMMAND_6($$dpth + 1, $$cr),
            () => this.matchCOMMAND_7($$dpth + 1, $$cr),
        ]);
    }
    public matchCOMMAND_1($$dpth: number, $$cr?: ContextRecorder): Nullable<COMMAND_1> {
        return this.matchBASIC_COMMAND($$dpth + 1, $$cr);
    }
    public matchCOMMAND_2($$dpth: number, $$cr?: ContextRecorder): Nullable<COMMAND_2> {
        return this.matchDATA_COMMAND($$dpth + 1, $$cr);
    }
    public matchCOMMAND_3($$dpth: number, $$cr?: ContextRecorder): Nullable<COMMAND_3> {
        return this.matchGRAPHICS_2D_COMMAND($$dpth + 1, $$cr);
    }
    public matchCOMMAND_4($$dpth: number, $$cr?: ContextRecorder): Nullable<COMMAND_4> {
        return this.matchGRAPHICS_3D_COMMAND($$dpth + 1, $$cr);
    }
    public matchCOMMAND_5($$dpth: number, $$cr?: ContextRecorder): Nullable<COMMAND_5> {
        return this.matchGUI_COMMAND($$dpth + 1, $$cr);
    }
    public matchCOMMAND_6($$dpth: number, $$cr?: ContextRecorder): Nullable<COMMAND_6> {
        return this.matchIO_COMMAND($$dpth + 1, $$cr);
    }
    public matchCOMMAND_7($$dpth: number, $$cr?: ContextRecorder): Nullable<COMMAND_7> {
        return this.matchSOUND_COMMAND($$dpth + 1, $$cr);
    }
    public matchBASIC_COMMAND($$dpth: number, $$cr?: ContextRecorder): Nullable<BASIC_COMMAND> {
        return this.choice<BASIC_COMMAND>([
            () => this.matchBASIC_COMMAND_1($$dpth + 1, $$cr),
            () => this.matchBASIC_COMMAND_2($$dpth + 1, $$cr),
            () => this.matchBASIC_COMMAND_3($$dpth + 1, $$cr),
            () => this.matchBASIC_COMMAND_4($$dpth + 1, $$cr),
        ]);
    }
    public matchBASIC_COMMAND_1($$dpth: number, $$cr?: ContextRecorder): Nullable<BASIC_COMMAND_1> {
        return this.matchBASIC_DIVERSE_COMMAND($$dpth + 1, $$cr);
    }
    public matchBASIC_COMMAND_2($$dpth: number, $$cr?: ContextRecorder): Nullable<BASIC_COMMAND_2> {
        return this.matchBASIC_MATHS_COMMAND($$dpth + 1, $$cr);
    }
    public matchBASIC_COMMAND_3($$dpth: number, $$cr?: ContextRecorder): Nullable<BASIC_COMMAND_3> {
        return this.matchBASIC_STRINGS_COMMAND($$dpth + 1, $$cr);
    }
    public matchBASIC_COMMAND_4($$dpth: number, $$cr?: ContextRecorder): Nullable<BASIC_COMMAND_4> {
        return this.matchBASIC_TIME_RANDOM_COMMAND($$dpth + 1, $$cr);
    }
    public matchBASIC_DIVERSE_COMMAND($$dpth: number, $$cr?: ContextRecorder): Nullable<BASIC_DIVERSE_COMMAND> {
        return this.regexAccept(String.raw`(?:)`, $$dpth + 1, $$cr);
    }
    public matchBASIC_MATHS_COMMAND($$dpth: number, $$cr?: ContextRecorder): Nullable<BASIC_MATHS_COMMAND> {
        return this.regexAccept(String.raw`(?:)`, $$dpth + 1, $$cr);
    }
    public matchBASIC_STRINGS_COMMAND($$dpth: number, $$cr?: ContextRecorder): Nullable<BASIC_STRINGS_COMMAND> {
        return this.regexAccept(String.raw`(?:)`, $$dpth + 1, $$cr);
    }
    public matchBASIC_TIME_RANDOM_COMMAND($$dpth: number, $$cr?: ContextRecorder): Nullable<BASIC_TIME_RANDOM_COMMAND> {
        return this.regexAccept(String.raw`(?:)`, $$dpth + 1, $$cr);
    }
    public matchDATA_COMMAND($$dpth: number, $$cr?: ContextRecorder): Nullable<DATA_COMMAND> {
        return this.choice<DATA_COMMAND>([
            () => this.matchDATA_COMMAND_1($$dpth + 1, $$cr),
            () => this.matchDATA_COMMAND_2($$dpth + 1, $$cr),
        ]);
    }
    public matchDATA_COMMAND_1($$dpth: number, $$cr?: ContextRecorder): Nullable<DATA_COMMAND_1> {
        return this.matchDATA_BANK_COMMAND($$dpth + 1, $$cr);
    }
    public matchDATA_COMMAND_2($$dpth: number, $$cr?: ContextRecorder): Nullable<DATA_COMMAND_2> {
        return this.matchDATA_FILE_SYSTEM_COMMAND($$dpth + 1, $$cr);
    }
    public matchDATA_BANK_COMMAND($$dpth: number, $$cr?: ContextRecorder): Nullable<DATA_BANK_COMMAND> {
        return this.regexAccept(String.raw`(?:)`, $$dpth + 1, $$cr);
    }
    public matchDATA_FILE_SYSTEM_COMMAND($$dpth: number, $$cr?: ContextRecorder): Nullable<DATA_FILE_SYSTEM_COMMAND> {
        return this.regexAccept(String.raw`(?:)`, $$dpth + 1, $$cr);
    }
    public matchGRAPHICS_2D_COMMAND($$dpth: number, $$cr?: ContextRecorder): Nullable<GRAPHICS_2D_COMMAND> {
        return this.choice<GRAPHICS_2D_COMMAND>([
            () => this.matchGRAPHICS_2D_COMMAND_1($$dpth + 1, $$cr),
            () => this.matchGRAPHICS_2D_COMMAND_2($$dpth + 1, $$cr),
            () => this.matchGRAPHICS_2D_COMMAND_3($$dpth + 1, $$cr),
            () => this.matchGRAPHICS_2D_COMMAND_4($$dpth + 1, $$cr),
            () => this.matchGRAPHICS_2D_COMMAND_5($$dpth + 1, $$cr),
            () => this.matchGRAPHICS_2D_COMMAND_6($$dpth + 1, $$cr),
            () => this.matchGRAPHICS_2D_COMMAND_7($$dpth + 1, $$cr),
        ]);
    }
    public matchGRAPHICS_2D_COMMAND_1($$dpth: number, $$cr?: ContextRecorder): Nullable<GRAPHICS_2D_COMMAND_1> {
        return this.matchGRAPHICS_2D_DISPLAY_COMMAND($$dpth + 1, $$cr);
    }
    public matchGRAPHICS_2D_COMMAND_2($$dpth: number, $$cr?: ContextRecorder): Nullable<GRAPHICS_2D_COMMAND_2> {
        return this.matchGRAPHICS_2D_GAMMA_COMMAND($$dpth + 1, $$cr);
    }
    public matchGRAPHICS_2D_COMMAND_3($$dpth: number, $$cr?: ContextRecorder): Nullable<GRAPHICS_2D_COMMAND_3> {
        return this.matchGRAPHICS_2D_GRAPHICS_COMMAND($$dpth + 1, $$cr);
    }
    public matchGRAPHICS_2D_COMMAND_4($$dpth: number, $$cr?: ContextRecorder): Nullable<GRAPHICS_2D_COMMAND_4> {
        return this.matchGRAPHICS_2D_IMAGES_COMMAND($$dpth + 1, $$cr);
    }
    public matchGRAPHICS_2D_COMMAND_5($$dpth: number, $$cr?: ContextRecorder): Nullable<GRAPHICS_2D_COMMAND_5> {
        return this.matchGRAPHICS_2D_MOVIES_COMMAND($$dpth + 1, $$cr);
    }
    public matchGRAPHICS_2D_COMMAND_6($$dpth: number, $$cr?: ContextRecorder): Nullable<GRAPHICS_2D_COMMAND_6> {
        return this.matchGRAPHICS_2D_PIXEL_COMMAND($$dpth + 1, $$cr);
    }
    public matchGRAPHICS_2D_COMMAND_7($$dpth: number, $$cr?: ContextRecorder): Nullable<GRAPHICS_2D_COMMAND_7> {
        return this.matchGRAPHICS_2D_TEXT_COMMAND($$dpth + 1, $$cr);
    }
    public matchGRAPHICS_2D_DISPLAY_COMMAND($$dpth: number, $$cr?: ContextRecorder): Nullable<GRAPHICS_2D_DISPLAY_COMMAND> {
        return this.regexAccept(String.raw`(?:)`, $$dpth + 1, $$cr);
    }
    public matchGRAPHICS_2D_GAMMA_COMMAND($$dpth: number, $$cr?: ContextRecorder): Nullable<GRAPHICS_2D_GAMMA_COMMAND> {
        return this.regexAccept(String.raw`(?:)`, $$dpth + 1, $$cr);
    }
    public matchGRAPHICS_2D_GRAPHICS_COMMAND($$dpth: number, $$cr?: ContextRecorder): Nullable<GRAPHICS_2D_GRAPHICS_COMMAND> {
        return this.choice<GRAPHICS_2D_GRAPHICS_COMMAND>([
            () => this.matchGRAPHICS_2D_GRAPHICS_COMMAND_1($$dpth + 1, $$cr),
            () => this.matchGRAPHICS_2D_GRAPHICS_COMMAND_2($$dpth + 1, $$cr),
            () => this.matchGRAPHICS_2D_GRAPHICS_COMMAND_3($$dpth + 1, $$cr),
            () => this.matchGRAPHICS_2D_GRAPHICS_COMMAND_4($$dpth + 1, $$cr),
            () => this.matchGRAPHICS_2D_GRAPHICS_COMMAND_5($$dpth + 1, $$cr),
            () => this.matchGRAPHICS_2D_GRAPHICS_COMMAND_6($$dpth + 1, $$cr),
        ]);
    }
    public matchGRAPHICS_2D_GRAPHICS_COMMAND_1($$dpth: number, $$cr?: ContextRecorder): Nullable<GRAPHICS_2D_GRAPHICS_COMMAND_1> {
        return this.matchCls($$dpth + 1, $$cr);
    }
    public matchGRAPHICS_2D_GRAPHICS_COMMAND_2($$dpth: number, $$cr?: ContextRecorder): Nullable<GRAPHICS_2D_GRAPHICS_COMMAND_2> {
        return this.matchClsColor($$dpth + 1, $$cr);
    }
    public matchGRAPHICS_2D_GRAPHICS_COMMAND_3($$dpth: number, $$cr?: ContextRecorder): Nullable<GRAPHICS_2D_GRAPHICS_COMMAND_3> {
        return this.matchColor($$dpth + 1, $$cr);
    }
    public matchGRAPHICS_2D_GRAPHICS_COMMAND_4($$dpth: number, $$cr?: ContextRecorder): Nullable<GRAPHICS_2D_GRAPHICS_COMMAND_4> {
        return this.matchLine($$dpth + 1, $$cr);
    }
    public matchGRAPHICS_2D_GRAPHICS_COMMAND_5($$dpth: number, $$cr?: ContextRecorder): Nullable<GRAPHICS_2D_GRAPHICS_COMMAND_5> {
        return this.matchOval($$dpth + 1, $$cr);
    }
    public matchGRAPHICS_2D_GRAPHICS_COMMAND_6($$dpth: number, $$cr?: ContextRecorder): Nullable<GRAPHICS_2D_GRAPHICS_COMMAND_6> {
        return this.matchRect($$dpth + 1, $$cr);
    }
    public matchCls($$dpth: number, $$cr?: ContextRecorder): Nullable<Cls> {
        return this.runner<Cls>($$dpth,
            (log) => {
                if (log) {
                    log("Cls");
                }
                let $$res: Nullable<Cls> = null;
                if (true
                    && this.regexAccept(String.raw`(?:[cC][lL][sS]\s*)`, $$dpth + 1, $$cr) !== null
                    && ((this.matchROOT($$dpth + 1, $$cr)) || true)
                ) {
                    $$res = {kind: ASTKinds.Cls, };
                }
                return $$res;
            }, $$cr)();
    }
    public matchClsColor($$dpth: number, $$cr?: ContextRecorder): Nullable<ClsColor> {
        return this.runner<ClsColor>($$dpth,
            (log) => {
                if (log) {
                    log("ClsColor");
                }
                let $scope$red: Nullable<NUMBER>;
                let $scope$green: Nullable<NUMBER>;
                let $scope$blue: Nullable<NUMBER>;
                let $$res: Nullable<ClsColor> = null;
                if (true
                    && this.regexAccept(String.raw`(?:[cC][lL][sS][cC][oO][lL][oO][rR]\s+)`, $$dpth + 1, $$cr) !== null
                    && ($scope$red = this.matchNUMBER($$dpth + 1, $$cr)) !== null
                    && this.regexAccept(String.raw`(?:,\s*)`, $$dpth + 1, $$cr) !== null
                    && ($scope$green = this.matchNUMBER($$dpth + 1, $$cr)) !== null
                    && this.regexAccept(String.raw`(?:,\s*)`, $$dpth + 1, $$cr) !== null
                    && ($scope$blue = this.matchNUMBER($$dpth + 1, $$cr)) !== null
                    && this.regexAccept(String.raw`(?:,\s*)`, $$dpth + 1, $$cr) !== null
                    && ((this.matchROOT($$dpth + 1, $$cr)) || true)
                ) {
                    $$res = {kind: ASTKinds.ClsColor, red: $scope$red, green: $scope$green, blue: $scope$blue};
                }
                return $$res;
            }, $$cr)();
    }
    public matchColor($$dpth: number, $$cr?: ContextRecorder): Nullable<Color> {
        return this.runner<Color>($$dpth,
            (log) => {
                if (log) {
                    log("Color");
                }
                let $scope$red: Nullable<NUMBER>;
                let $scope$green: Nullable<NUMBER>;
                let $scope$blue: Nullable<NUMBER>;
                let $$res: Nullable<Color> = null;
                if (true
                    && this.regexAccept(String.raw`(?:[cC][oO][lL][oO][rR]\s+)`, $$dpth + 1, $$cr) !== null
                    && ($scope$red = this.matchNUMBER($$dpth + 1, $$cr)) !== null
                    && this.regexAccept(String.raw`(?:,\s*)`, $$dpth + 1, $$cr) !== null
                    && ($scope$green = this.matchNUMBER($$dpth + 1, $$cr)) !== null
                    && this.regexAccept(String.raw`(?:,\s*)`, $$dpth + 1, $$cr) !== null
                    && ($scope$blue = this.matchNUMBER($$dpth + 1, $$cr)) !== null
                    && this.regexAccept(String.raw`(?:,\s*)`, $$dpth + 1, $$cr) !== null
                    && ((this.matchROOT($$dpth + 1, $$cr)) || true)
                ) {
                    $$res = {kind: ASTKinds.Color, red: $scope$red, green: $scope$green, blue: $scope$blue};
                }
                return $$res;
            }, $$cr)();
    }
    public matchLine($$dpth: number, $$cr?: ContextRecorder): Nullable<Line> {
        return this.runner<Line>($$dpth,
            (log) => {
                if (log) {
                    log("Line");
                }
                let $scope$beginX: Nullable<NUMBER>;
                let $scope$beginY: Nullable<NUMBER>;
                let $scope$endX: Nullable<NUMBER>;
                let $scope$endY: Nullable<NUMBER>;
                let $$res: Nullable<Line> = null;
                if (true
                    && this.regexAccept(String.raw`(?:[lL][iI][nN][eE]\s+)`, $$dpth + 1, $$cr) !== null
                    && ($scope$beginX = this.matchNUMBER($$dpth + 1, $$cr)) !== null
                    && this.regexAccept(String.raw`(?:,\s*)`, $$dpth + 1, $$cr) !== null
                    && ($scope$beginY = this.matchNUMBER($$dpth + 1, $$cr)) !== null
                    && this.regexAccept(String.raw`(?:,\s*)`, $$dpth + 1, $$cr) !== null
                    && ($scope$endX = this.matchNUMBER($$dpth + 1, $$cr)) !== null
                    && this.regexAccept(String.raw`(?:,\s*)`, $$dpth + 1, $$cr) !== null
                    && ($scope$endY = this.matchNUMBER($$dpth + 1, $$cr)) !== null
                    && this.regexAccept(String.raw`(?:,\s*)`, $$dpth + 1, $$cr) !== null
                    && ((this.matchROOT($$dpth + 1, $$cr)) || true)
                ) {
                    $$res = {kind: ASTKinds.Line, beginX: $scope$beginX, beginY: $scope$beginY, endX: $scope$endX, endY: $scope$endY};
                }
                return $$res;
            }, $$cr)();
    }
    public matchOval($$dpth: number, $$cr?: ContextRecorder): Nullable<Oval> {
        return this.runner<Oval>($$dpth,
            (log) => {
                if (log) {
                    log("Oval");
                }
                let $scope$x: Nullable<NUMBER>;
                let $scope$y: Nullable<NUMBER>;
                let $scope$width: Nullable<NUMBER>;
                let $scope$height: Nullable<NUMBER>;
                let $$res: Nullable<Oval> = null;
                if (true
                    && this.regexAccept(String.raw`(?:[oO][vV][aA][lL]\s+)`, $$dpth + 1, $$cr) !== null
                    && ($scope$x = this.matchNUMBER($$dpth + 1, $$cr)) !== null
                    && this.regexAccept(String.raw`(?:,\s*)`, $$dpth + 1, $$cr) !== null
                    && ($scope$y = this.matchNUMBER($$dpth + 1, $$cr)) !== null
                    && this.regexAccept(String.raw`(?:,\s?)`, $$dpth + 1, $$cr) !== null
                    && ($scope$width = this.matchNUMBER($$dpth + 1, $$cr)) !== null
                    && this.regexAccept(String.raw`(?:,\s*)`, $$dpth + 1, $$cr) !== null
                    && ($scope$height = this.matchNUMBER($$dpth + 1, $$cr)) !== null
                    && this.regexAccept(String.raw`(?:,\s*)`, $$dpth + 1, $$cr) !== null
                    && ((this.matchROOT($$dpth + 1, $$cr)) || true)
                ) {
                    $$res = {kind: ASTKinds.Oval, x: $scope$x, y: $scope$y, width: $scope$width, height: $scope$height};
                }
                return $$res;
            }, $$cr)();
    }
    public matchRect($$dpth: number, $$cr?: ContextRecorder): Nullable<Rect> {
        return this.runner<Rect>($$dpth,
            (log) => {
                if (log) {
                    log("Rect");
                }
                let $scope$x: Nullable<NUMBER>;
                let $scope$y: Nullable<NUMBER>;
                let $scope$width: Nullable<NUMBER>;
                let $scope$height: Nullable<NUMBER>;
                let $$res: Nullable<Rect> = null;
                if (true
                    && this.regexAccept(String.raw`(?:[rR][eE][cC][tT]\s+)`, $$dpth + 1, $$cr) !== null
                    && ($scope$x = this.matchNUMBER($$dpth + 1, $$cr)) !== null
                    && this.regexAccept(String.raw`(?:,\s*)`, $$dpth + 1, $$cr) !== null
                    && ($scope$y = this.matchNUMBER($$dpth + 1, $$cr)) !== null
                    && this.regexAccept(String.raw`(?:,\s*)`, $$dpth + 1, $$cr) !== null
                    && ($scope$width = this.matchNUMBER($$dpth + 1, $$cr)) !== null
                    && this.regexAccept(String.raw`(?:,\s*)`, $$dpth + 1, $$cr) !== null
                    && ($scope$height = this.matchNUMBER($$dpth + 1, $$cr)) !== null
                    && this.regexAccept(String.raw`(?:,\s*)`, $$dpth + 1, $$cr) !== null
                    && ((this.matchROOT($$dpth + 1, $$cr)) || true)
                ) {
                    $$res = {kind: ASTKinds.Rect, x: $scope$x, y: $scope$y, width: $scope$width, height: $scope$height};
                }
                return $$res;
            }, $$cr)();
    }
    public matchGRAPHICS_2D_IMAGES_COMMAND($$dpth: number, $$cr?: ContextRecorder): Nullable<GRAPHICS_2D_IMAGES_COMMAND> {
        return this.regexAccept(String.raw`(?:)`, $$dpth + 1, $$cr);
    }
    public matchGRAPHICS_2D_MOVIES_COMMAND($$dpth: number, $$cr?: ContextRecorder): Nullable<GRAPHICS_2D_MOVIES_COMMAND> {
        return this.regexAccept(String.raw`(?:)`, $$dpth + 1, $$cr);
    }
    public matchGRAPHICS_2D_PIXEL_COMMAND($$dpth: number, $$cr?: ContextRecorder): Nullable<GRAPHICS_2D_PIXEL_COMMAND> {
        return this.regexAccept(String.raw`(?:)`, $$dpth + 1, $$cr);
    }
    public matchGRAPHICS_2D_TEXT_COMMAND($$dpth: number, $$cr?: ContextRecorder): Nullable<GRAPHICS_2D_TEXT_COMMAND> {
        return this.regexAccept(String.raw`(?:)`, $$dpth + 1, $$cr);
    }
    public matchGRAPHICS_3D_COMMAND($$dpth: number, $$cr?: ContextRecorder): Nullable<GRAPHICS_3D_COMMAND> {
        return this.choice<GRAPHICS_3D_COMMAND>([
            () => this.matchGRAPHICS_3D_COMMAND_1($$dpth + 1, $$cr),
            () => this.matchGRAPHICS_3D_COMMAND_2($$dpth + 1, $$cr),
            () => this.matchGRAPHICS_3D_COMMAND_3($$dpth + 1, $$cr),
            () => this.matchGRAPHICS_3D_COMMAND_4($$dpth + 1, $$cr),
            () => this.matchGRAPHICS_3D_COMMAND_5($$dpth + 1, $$cr),
            () => this.matchGRAPHICS_3D_COMMAND_6($$dpth + 1, $$cr),
            () => this.matchGRAPHICS_3D_COMMAND_7($$dpth + 1, $$cr),
            () => this.matchGRAPHICS_3D_COMMAND_8($$dpth + 1, $$cr),
            () => this.matchGRAPHICS_3D_COMMAND_9($$dpth + 1, $$cr),
            () => this.matchGRAPHICS_3D_COMMAND_10($$dpth + 1, $$cr),
            () => this.matchGRAPHICS_3D_COMMAND_11($$dpth + 1, $$cr),
            () => this.matchGRAPHICS_3D_COMMAND_12($$dpth + 1, $$cr),
            () => this.matchGRAPHICS_3D_COMMAND_13($$dpth + 1, $$cr),
            () => this.matchGRAPHICS_3D_COMMAND_14($$dpth + 1, $$cr),
            () => this.matchGRAPHICS_3D_COMMAND_15($$dpth + 1, $$cr),
            () => this.matchGRAPHICS_3D_COMMAND_16($$dpth + 1, $$cr),
            () => this.matchGRAPHICS_3D_COMMAND_17($$dpth + 1, $$cr),
            () => this.matchGRAPHICS_3D_COMMAND_18($$dpth + 1, $$cr),
        ]);
    }
    public matchGRAPHICS_3D_COMMAND_1($$dpth: number, $$cr?: ContextRecorder): Nullable<GRAPHICS_3D_COMMAND_1> {
        return this.matchGRAPHICS_3D_ANIMATIONS_COMMAND($$dpth + 1, $$cr);
    }
    public matchGRAPHICS_3D_COMMAND_2($$dpth: number, $$cr?: ContextRecorder): Nullable<GRAPHICS_3D_COMMAND_2> {
        return this.matchGRAPHICS_3D_BRUSHES_COMMAND($$dpth + 1, $$cr);
    }
    public matchGRAPHICS_3D_COMMAND_3($$dpth: number, $$cr?: ContextRecorder): Nullable<GRAPHICS_3D_COMMAND_3> {
        return this.matchGRAPHICS_3D_CAMERA_COMMAND($$dpth + 1, $$cr);
    }
    public matchGRAPHICS_3D_COMMAND_4($$dpth: number, $$cr?: ContextRecorder): Nullable<GRAPHICS_3D_COMMAND_4> {
        return this.matchGRAPHICS_3D_COLLISIONS_COMMAND($$dpth + 1, $$cr);
    }
    public matchGRAPHICS_3D_COMMAND_5($$dpth: number, $$cr?: ContextRecorder): Nullable<GRAPHICS_3D_COMMAND_5> {
        return this.matchGRAPHICS_3D_CONTROLS_COMMAND($$dpth + 1, $$cr);
    }
    public matchGRAPHICS_3D_COMMAND_6($$dpth: number, $$cr?: ContextRecorder): Nullable<GRAPHICS_3D_COMMAND_6> {
        return this.matchGRAPHICS_3D_COORDINATES_COMMAND($$dpth + 1, $$cr);
    }
    public matchGRAPHICS_3D_COMMAND_7($$dpth: number, $$cr?: ContextRecorder): Nullable<GRAPHICS_3D_COMMAND_7> {
        return this.matchGRAPHICS_3D_DIVERSE_COMMAND($$dpth + 1, $$cr);
    }
    public matchGRAPHICS_3D_COMMAND_8($$dpth: number, $$cr?: ContextRecorder): Nullable<GRAPHICS_3D_COMMAND_8> {
        return this.matchGRAPHICS_3D_LIGHT_SHADOW_COMMAND($$dpth + 1, $$cr);
    }
    public matchGRAPHICS_3D_COMMAND_9($$dpth: number, $$cr?: ContextRecorder): Nullable<GRAPHICS_3D_COMMAND_9> {
        return this.matchGRAPHICS_3D_MESHES_COMMAND($$dpth + 1, $$cr);
    }
    public matchGRAPHICS_3D_COMMAND_10($$dpth: number, $$cr?: ContextRecorder): Nullable<GRAPHICS_3D_COMMAND_10> {
        return this.matchGRAPHICS_3D_PICKING_COMMAND($$dpth + 1, $$cr);
    }
    public matchGRAPHICS_3D_COMMAND_11($$dpth: number, $$cr?: ContextRecorder): Nullable<GRAPHICS_3D_COMMAND_11> {
        return this.matchGRAPHICS_3D_SCENE_COMMAND($$dpth + 1, $$cr);
    }
    public matchGRAPHICS_3D_COMMAND_12($$dpth: number, $$cr?: ContextRecorder): Nullable<GRAPHICS_3D_COMMAND_12> {
        return this.matchGRAPHICS_3D_SCENERY_COMMAND($$dpth + 1, $$cr);
    }
    public matchGRAPHICS_3D_COMMAND_13($$dpth: number, $$cr?: ContextRecorder): Nullable<GRAPHICS_3D_COMMAND_13> {
        return this.matchGRAPHICS_3D_SCREEN_COMMAND($$dpth + 1, $$cr);
    }
    public matchGRAPHICS_3D_COMMAND_14($$dpth: number, $$cr?: ContextRecorder): Nullable<GRAPHICS_3D_COMMAND_14> {
        return this.matchGRAPHICS_3D_SPRITES_COMMAND($$dpth + 1, $$cr);
    }
    public matchGRAPHICS_3D_COMMAND_15($$dpth: number, $$cr?: ContextRecorder): Nullable<GRAPHICS_3D_COMMAND_15> {
        return this.matchGRAPHICS_3D_STATUS_COMMAND($$dpth + 1, $$cr);
    }
    public matchGRAPHICS_3D_COMMAND_16($$dpth: number, $$cr?: ContextRecorder): Nullable<GRAPHICS_3D_COMMAND_16> {
        return this.matchGRAPHICS_3D_SURFACES_COMMAND($$dpth + 1, $$cr);
    }
    public matchGRAPHICS_3D_COMMAND_17($$dpth: number, $$cr?: ContextRecorder): Nullable<GRAPHICS_3D_COMMAND_17> {
        return this.matchGRAPHICS_3D_TERRAIN_COMMAND($$dpth + 1, $$cr);
    }
    public matchGRAPHICS_3D_COMMAND_18($$dpth: number, $$cr?: ContextRecorder): Nullable<GRAPHICS_3D_COMMAND_18> {
        return this.matchGRAPHICS_3D_TEXTURES_COMMAND($$dpth + 1, $$cr);
    }
    public matchGRAPHICS_3D_ANIMATIONS_COMMAND($$dpth: number, $$cr?: ContextRecorder): Nullable<GRAPHICS_3D_ANIMATIONS_COMMAND> {
        return this.regexAccept(String.raw`(?:)`, $$dpth + 1, $$cr);
    }
    public matchGRAPHICS_3D_BRUSHES_COMMAND($$dpth: number, $$cr?: ContextRecorder): Nullable<GRAPHICS_3D_BRUSHES_COMMAND> {
        return this.regexAccept(String.raw`(?:)`, $$dpth + 1, $$cr);
    }
    public matchGRAPHICS_3D_CAMERA_COMMAND($$dpth: number, $$cr?: ContextRecorder): Nullable<GRAPHICS_3D_CAMERA_COMMAND> {
        return this.regexAccept(String.raw`(?:)`, $$dpth + 1, $$cr);
    }
    public matchGRAPHICS_3D_COLLISIONS_COMMAND($$dpth: number, $$cr?: ContextRecorder): Nullable<GRAPHICS_3D_COLLISIONS_COMMAND> {
        return this.regexAccept(String.raw`(?:)`, $$dpth + 1, $$cr);
    }
    public matchGRAPHICS_3D_CONTROLS_COMMAND($$dpth: number, $$cr?: ContextRecorder): Nullable<GRAPHICS_3D_CONTROLS_COMMAND> {
        return this.regexAccept(String.raw`(?:)`, $$dpth + 1, $$cr);
    }
    public matchGRAPHICS_3D_COORDINATES_COMMAND($$dpth: number, $$cr?: ContextRecorder): Nullable<GRAPHICS_3D_COORDINATES_COMMAND> {
        return this.regexAccept(String.raw`(?:)`, $$dpth + 1, $$cr);
    }
    public matchGRAPHICS_3D_DIVERSE_COMMAND($$dpth: number, $$cr?: ContextRecorder): Nullable<GRAPHICS_3D_DIVERSE_COMMAND> {
        return this.regexAccept(String.raw`(?:)`, $$dpth + 1, $$cr);
    }
    public matchGRAPHICS_3D_LIGHT_SHADOW_COMMAND($$dpth: number, $$cr?: ContextRecorder): Nullable<GRAPHICS_3D_LIGHT_SHADOW_COMMAND> {
        return this.regexAccept(String.raw`(?:)`, $$dpth + 1, $$cr);
    }
    public matchGRAPHICS_3D_MESHES_COMMAND($$dpth: number, $$cr?: ContextRecorder): Nullable<GRAPHICS_3D_MESHES_COMMAND> {
        return this.regexAccept(String.raw`(?:)`, $$dpth + 1, $$cr);
    }
    public matchGRAPHICS_3D_PICKING_COMMAND($$dpth: number, $$cr?: ContextRecorder): Nullable<GRAPHICS_3D_PICKING_COMMAND> {
        return this.regexAccept(String.raw`(?:)`, $$dpth + 1, $$cr);
    }
    public matchGRAPHICS_3D_SCENE_COMMAND($$dpth: number, $$cr?: ContextRecorder): Nullable<GRAPHICS_3D_SCENE_COMMAND> {
        return this.regexAccept(String.raw`(?:)`, $$dpth + 1, $$cr);
    }
    public matchGRAPHICS_3D_SCENERY_COMMAND($$dpth: number, $$cr?: ContextRecorder): Nullable<GRAPHICS_3D_SCENERY_COMMAND> {
        return this.regexAccept(String.raw`(?:)`, $$dpth + 1, $$cr);
    }
    public matchGRAPHICS_3D_SCREEN_COMMAND($$dpth: number, $$cr?: ContextRecorder): Nullable<GRAPHICS_3D_SCREEN_COMMAND> {
        return this.regexAccept(String.raw`(?:)`, $$dpth + 1, $$cr);
    }
    public matchGRAPHICS_3D_SPRITES_COMMAND($$dpth: number, $$cr?: ContextRecorder): Nullable<GRAPHICS_3D_SPRITES_COMMAND> {
        return this.regexAccept(String.raw`(?:)`, $$dpth + 1, $$cr);
    }
    public matchGRAPHICS_3D_STATUS_COMMAND($$dpth: number, $$cr?: ContextRecorder): Nullable<GRAPHICS_3D_STATUS_COMMAND> {
        return this.regexAccept(String.raw`(?:)`, $$dpth + 1, $$cr);
    }
    public matchGRAPHICS_3D_SURFACES_COMMAND($$dpth: number, $$cr?: ContextRecorder): Nullable<GRAPHICS_3D_SURFACES_COMMAND> {
        return this.regexAccept(String.raw`(?:)`, $$dpth + 1, $$cr);
    }
    public matchGRAPHICS_3D_TERRAIN_COMMAND($$dpth: number, $$cr?: ContextRecorder): Nullable<GRAPHICS_3D_TERRAIN_COMMAND> {
        return this.regexAccept(String.raw`(?:)`, $$dpth + 1, $$cr);
    }
    public matchGRAPHICS_3D_TEXTURES_COMMAND($$dpth: number, $$cr?: ContextRecorder): Nullable<GRAPHICS_3D_TEXTURES_COMMAND> {
        return this.regexAccept(String.raw`(?:)`, $$dpth + 1, $$cr);
    }
    public matchGUI_COMMAND($$dpth: number, $$cr?: ContextRecorder): Nullable<GUI_COMMAND> {
        return this.choice<GUI_COMMAND>([
            () => this.matchGUI_COMMAND_1($$dpth + 1, $$cr),
            () => this.matchGUI_COMMAND_2($$dpth + 1, $$cr),
            () => this.matchGUI_COMMAND_3($$dpth + 1, $$cr),
            () => this.matchGUI_COMMAND_4($$dpth + 1, $$cr),
            () => this.matchGUI_COMMAND_5($$dpth + 1, $$cr),
            () => this.matchGUI_COMMAND_6($$dpth + 1, $$cr),
            () => this.matchGUI_COMMAND_7($$dpth + 1, $$cr),
            () => this.matchGUI_COMMAND_8($$dpth + 1, $$cr),
            () => this.matchGUI_COMMAND_9($$dpth + 1, $$cr),
            () => this.matchGUI_COMMAND_10($$dpth + 1, $$cr),
            () => this.matchGUI_COMMAND_11($$dpth + 1, $$cr),
            () => this.matchGUI_COMMAND_12($$dpth + 1, $$cr),
            () => this.matchGUI_COMMAND_13($$dpth + 1, $$cr),
            () => this.matchGUI_COMMAND_14($$dpth + 1, $$cr),
            () => this.matchGUI_COMMAND_15($$dpth + 1, $$cr),
            () => this.matchGUI_COMMAND_16($$dpth + 1, $$cr),
            () => this.matchGUI_COMMAND_17($$dpth + 1, $$cr),
            () => this.matchGUI_COMMAND_18($$dpth + 1, $$cr),
            () => this.matchGUI_COMMAND_19($$dpth + 1, $$cr),
        ]);
    }
    public matchGUI_COMMAND_1($$dpth: number, $$cr?: ContextRecorder): Nullable<GUI_COMMAND_1> {
        return this.matchGUI_BUTTON_COMMAND($$dpth + 1, $$cr);
    }
    public matchGUI_COMMAND_2($$dpth: number, $$cr?: ContextRecorder): Nullable<GUI_COMMAND_2> {
        return this.matchGUI_CANVAS_COMMAND($$dpth + 1, $$cr);
    }
    public matchGUI_COMMAND_3($$dpth: number, $$cr?: ContextRecorder): Nullable<GUI_COMMAND_3> {
        return this.matchGUI_DESKTOP_COMMAND($$dpth + 1, $$cr);
    }
    public matchGUI_COMMAND_4($$dpth: number, $$cr?: ContextRecorder): Nullable<GUI_COMMAND_4> {
        return this.matchGUI_DIVERSE_COMMAND($$dpth + 1, $$cr);
    }
    public matchGUI_COMMAND_5($$dpth: number, $$cr?: ContextRecorder): Nullable<GUI_COMMAND_5> {
        return this.matchGUI_EVENT_COMMAND($$dpth + 1, $$cr);
    }
    public matchGUI_COMMAND_6($$dpth: number, $$cr?: ContextRecorder): Nullable<GUI_COMMAND_6> {
        return this.matchGUI_GADGET_COMMAND($$dpth + 1, $$cr);
    }
    public matchGUI_COMMAND_7($$dpth: number, $$cr?: ContextRecorder): Nullable<GUI_COMMAND_7> {
        return this.matchGUI_HTML_COMMAND($$dpth + 1, $$cr);
    }
    public matchGUI_COMMAND_8($$dpth: number, $$cr?: ContextRecorder): Nullable<GUI_COMMAND_8> {
        return this.matchGUI_ICON_STRIP_COMMAND($$dpth + 1, $$cr);
    }
    public matchGUI_COMMAND_9($$dpth: number, $$cr?: ContextRecorder): Nullable<GUI_COMMAND_9> {
        return this.matchGUI_LIST_TABBER_COMMAND($$dpth + 1, $$cr);
    }
    public matchGUI_COMMAND_10($$dpth: number, $$cr?: ContextRecorder): Nullable<GUI_COMMAND_10> {
        return this.matchGUI_MENU_COMMAND($$dpth + 1, $$cr);
    }
    public matchGUI_COMMAND_11($$dpth: number, $$cr?: ContextRecorder): Nullable<GUI_COMMAND_11> {
        return this.matchGUI_PANEL_COMMAND($$dpth + 1, $$cr);
    }
    public matchGUI_COMMAND_12($$dpth: number, $$cr?: ContextRecorder): Nullable<GUI_COMMAND_12> {
        return this.matchGUI_PROGRESS_BAR_COMMAND($$dpth + 1, $$cr);
    }
    public matchGUI_COMMAND_13($$dpth: number, $$cr?: ContextRecorder): Nullable<GUI_COMMAND_13> {
        return this.matchGUI_REQUEST_COMMAND($$dpth + 1, $$cr);
    }
    public matchGUI_COMMAND_14($$dpth: number, $$cr?: ContextRecorder): Nullable<GUI_COMMAND_14> {
        return this.matchGUI_SLIDER_COMMAND($$dpth + 1, $$cr);
    }
    public matchGUI_COMMAND_15($$dpth: number, $$cr?: ContextRecorder): Nullable<GUI_COMMAND_15> {
        return this.matchGUI_TEXT_AREA_COMMAND($$dpth + 1, $$cr);
    }
    public matchGUI_COMMAND_16($$dpth: number, $$cr?: ContextRecorder): Nullable<GUI_COMMAND_16> {
        return this.matchGUI_TEXT_FIELD_COMMAND($$dpth + 1, $$cr);
    }
    public matchGUI_COMMAND_17($$dpth: number, $$cr?: ContextRecorder): Nullable<GUI_COMMAND_17> {
        return this.matchGUI_TOOLBAR_COMMAND($$dpth + 1, $$cr);
    }
    public matchGUI_COMMAND_18($$dpth: number, $$cr?: ContextRecorder): Nullable<GUI_COMMAND_18> {
        return this.matchGUI_TREE_VIEW_COMMAND($$dpth + 1, $$cr);
    }
    public matchGUI_COMMAND_19($$dpth: number, $$cr?: ContextRecorder): Nullable<GUI_COMMAND_19> {
        return this.matchGUI_WINDOW_COMMAND($$dpth + 1, $$cr);
    }
    public matchGUI_BUTTON_COMMAND($$dpth: number, $$cr?: ContextRecorder): Nullable<GUI_BUTTON_COMMAND> {
        return this.regexAccept(String.raw`(?:)`, $$dpth + 1, $$cr);
    }
    public matchGUI_CANVAS_COMMAND($$dpth: number, $$cr?: ContextRecorder): Nullable<GUI_CANVAS_COMMAND> {
        return this.regexAccept(String.raw`(?:)`, $$dpth + 1, $$cr);
    }
    public matchGUI_DESKTOP_COMMAND($$dpth: number, $$cr?: ContextRecorder): Nullable<GUI_DESKTOP_COMMAND> {
        return this.regexAccept(String.raw`(?:)`, $$dpth + 1, $$cr);
    }
    public matchGUI_DIVERSE_COMMAND($$dpth: number, $$cr?: ContextRecorder): Nullable<GUI_DIVERSE_COMMAND> {
        return this.regexAccept(String.raw`(?:)`, $$dpth + 1, $$cr);
    }
    public matchGUI_EVENT_COMMAND($$dpth: number, $$cr?: ContextRecorder): Nullable<GUI_EVENT_COMMAND> {
        return this.regexAccept(String.raw`(?:)`, $$dpth + 1, $$cr);
    }
    public matchGUI_GADGET_COMMAND($$dpth: number, $$cr?: ContextRecorder): Nullable<GUI_GADGET_COMMAND> {
        return this.regexAccept(String.raw`(?:)`, $$dpth + 1, $$cr);
    }
    public matchGUI_HTML_COMMAND($$dpth: number, $$cr?: ContextRecorder): Nullable<GUI_HTML_COMMAND> {
        return this.regexAccept(String.raw`(?:)`, $$dpth + 1, $$cr);
    }
    public matchGUI_ICON_STRIP_COMMAND($$dpth: number, $$cr?: ContextRecorder): Nullable<GUI_ICON_STRIP_COMMAND> {
        return this.regexAccept(String.raw`(?:)`, $$dpth + 1, $$cr);
    }
    public matchGUI_LIST_TABBER_COMMAND($$dpth: number, $$cr?: ContextRecorder): Nullable<GUI_LIST_TABBER_COMMAND> {
        return this.regexAccept(String.raw`(?:)`, $$dpth + 1, $$cr);
    }
    public matchGUI_MENU_COMMAND($$dpth: number, $$cr?: ContextRecorder): Nullable<GUI_MENU_COMMAND> {
        return this.regexAccept(String.raw`(?:)`, $$dpth + 1, $$cr);
    }
    public matchGUI_PANEL_COMMAND($$dpth: number, $$cr?: ContextRecorder): Nullable<GUI_PANEL_COMMAND> {
        return this.regexAccept(String.raw`(?:)`, $$dpth + 1, $$cr);
    }
    public matchGUI_PROGRESS_BAR_COMMAND($$dpth: number, $$cr?: ContextRecorder): Nullable<GUI_PROGRESS_BAR_COMMAND> {
        return this.regexAccept(String.raw`(?:)`, $$dpth + 1, $$cr);
    }
    public matchGUI_REQUEST_COMMAND($$dpth: number, $$cr?: ContextRecorder): Nullable<GUI_REQUEST_COMMAND> {
        return this.regexAccept(String.raw`(?:)`, $$dpth + 1, $$cr);
    }
    public matchGUI_SLIDER_COMMAND($$dpth: number, $$cr?: ContextRecorder): Nullable<GUI_SLIDER_COMMAND> {
        return this.regexAccept(String.raw`(?:)`, $$dpth + 1, $$cr);
    }
    public matchGUI_TEXT_AREA_COMMAND($$dpth: number, $$cr?: ContextRecorder): Nullable<GUI_TEXT_AREA_COMMAND> {
        return this.regexAccept(String.raw`(?:)`, $$dpth + 1, $$cr);
    }
    public matchGUI_TEXT_FIELD_COMMAND($$dpth: number, $$cr?: ContextRecorder): Nullable<GUI_TEXT_FIELD_COMMAND> {
        return this.regexAccept(String.raw`(?:)`, $$dpth + 1, $$cr);
    }
    public matchGUI_TOOLBAR_COMMAND($$dpth: number, $$cr?: ContextRecorder): Nullable<GUI_TOOLBAR_COMMAND> {
        return this.regexAccept(String.raw`(?:)`, $$dpth + 1, $$cr);
    }
    public matchGUI_TREE_VIEW_COMMAND($$dpth: number, $$cr?: ContextRecorder): Nullable<GUI_TREE_VIEW_COMMAND> {
        return this.regexAccept(String.raw`(?:)`, $$dpth + 1, $$cr);
    }
    public matchGUI_WINDOW_COMMAND($$dpth: number, $$cr?: ContextRecorder): Nullable<GUI_WINDOW_COMMAND> {
        return this.regexAccept(String.raw`(?:)`, $$dpth + 1, $$cr);
    }
    public matchIO_COMMAND($$dpth: number, $$cr?: ContextRecorder): Nullable<IO_COMMAND> {
        return this.choice<IO_COMMAND>([
            () => this.matchIO_COMMAND_1($$dpth + 1, $$cr),
            () => this.matchIO_COMMAND_2($$dpth + 1, $$cr),
            () => this.matchIO_COMMAND_3($$dpth + 1, $$cr),
        ]);
    }
    public matchIO_COMMAND_1($$dpth: number, $$cr?: ContextRecorder): Nullable<IO_COMMAND_1> {
        return this.matchIO_GAMEPAD_COMMAND($$dpth + 1, $$cr);
    }
    public matchIO_COMMAND_2($$dpth: number, $$cr?: ContextRecorder): Nullable<IO_COMMAND_2> {
        return this.matchIO_KEYBOARD_COMMAND($$dpth + 1, $$cr);
    }
    public matchIO_COMMAND_3($$dpth: number, $$cr?: ContextRecorder): Nullable<IO_COMMAND_3> {
        return this.matchIO_MOUSE_COMMAND($$dpth + 1, $$cr);
    }
    public matchIO_GAMEPAD_COMMAND($$dpth: number, $$cr?: ContextRecorder): Nullable<IO_GAMEPAD_COMMAND> {
        return this.regexAccept(String.raw`(?:)`, $$dpth + 1, $$cr);
    }
    public matchIO_KEYBOARD_COMMAND($$dpth: number, $$cr?: ContextRecorder): Nullable<IO_KEYBOARD_COMMAND> {
        return this.regexAccept(String.raw`(?:)`, $$dpth + 1, $$cr);
    }
    public matchIO_MOUSE_COMMAND($$dpth: number, $$cr?: ContextRecorder): Nullable<IO_MOUSE_COMMAND> {
        return this.regexAccept(String.raw`(?:)`, $$dpth + 1, $$cr);
    }
    public matchSOUND_COMMAND($$dpth: number, $$cr?: ContextRecorder): Nullable<SOUND_COMMAND> {
        return this.choice<SOUND_COMMAND>([
            () => this.matchSOUND_COMMAND_1($$dpth + 1, $$cr),
            () => this.matchSOUND_COMMAND_2($$dpth + 1, $$cr),
            () => this.matchSOUND_COMMAND_3($$dpth + 1, $$cr),
        ]);
    }
    public matchSOUND_COMMAND_1($$dpth: number, $$cr?: ContextRecorder): Nullable<SOUND_COMMAND_1> {
        return this.matchSOUND_3D_COMMAND($$dpth + 1, $$cr);
    }
    public matchSOUND_COMMAND_2($$dpth: number, $$cr?: ContextRecorder): Nullable<SOUND_COMMAND_2> {
        return this.matchSOUND_CHANNELS_COMMAND($$dpth + 1, $$cr);
    }
    public matchSOUND_COMMAND_3($$dpth: number, $$cr?: ContextRecorder): Nullable<SOUND_COMMAND_3> {
        return this.matchSOUND_MUSIC_SAMPLES_COMMAND($$dpth + 1, $$cr);
    }
    public matchSOUND_3D_COMMAND($$dpth: number, $$cr?: ContextRecorder): Nullable<SOUND_3D_COMMAND> {
        return this.regexAccept(String.raw`(?:)`, $$dpth + 1, $$cr);
    }
    public matchSOUND_CHANNELS_COMMAND($$dpth: number, $$cr?: ContextRecorder): Nullable<SOUND_CHANNELS_COMMAND> {
        return this.regexAccept(String.raw`(?:)`, $$dpth + 1, $$cr);
    }
    public matchSOUND_MUSIC_SAMPLES_COMMAND($$dpth: number, $$cr?: ContextRecorder): Nullable<SOUND_MUSIC_SAMPLES_COMMAND> {
        return this.regexAccept(String.raw`(?:)`, $$dpth + 1, $$cr);
    }
    public test(): boolean {
        const mrk = this.mark();
        const res = this.matchROOT(0);
        const ans = res !== null && this.finished();
        this.reset(mrk);
        return ans;
    }
    public parse(): ParseResult {
        const mrk = this.mark();
        const res = this.matchROOT(0);
        if (res && this.finished()) {
            return new ParseResult(res, null);
        }
        this.reset(mrk);
        const rec = new ErrorTracker();
        this.matchROOT(0, rec);
        return new ParseResult(res,
            rec.getErr() ?? new SyntaxErr(this.mark(), new Set(["$EOF"]), new Set([])));
    }
    public mark(): PosInfo {
        return this.pos;
    }
    private loop<T>(func: $$RuleType<T>, star: boolean = false): Nullable<T[]> {
        const mrk = this.mark();
        const res: T[] = [];
        for (;;) {
            const t = func();
            if (t === null) {
                break;
            }
            res.push(t);
        }
        if (star || res.length > 0) {
            return res;
        }
        this.reset(mrk);
        return null;
    }
    private runner<T>($$dpth: number, fn: $$RuleType<T>, cr?: ContextRecorder): $$RuleType<T> {
        return () => {
            const mrk = this.mark();
            const res = cr ? (() => {
                const extraInfo: string[] = [];
                const result = fn((msg: string) => extraInfo.push(msg));
                cr.record(mrk, $$dpth, result, this.negating, extraInfo);
                return result;
            })() : fn();
            if (res !== null) {
                return res;
            }
            this.reset(mrk);
            return null;
        };
    }
    private choice<T>(fns: Array<$$RuleType<T>>): Nullable<T> {
        for (const f of fns) {
            const res = f();
            if (res !== null) {
                return res;
            }
        }
        return null;
    }
    private regexAccept(match: string, dpth: number, cr?: ContextRecorder): Nullable<string> {
        return this.runner<string>(dpth,
            (log) => {
                if (log) {
                    if (this.negating) {
                        log("$$!StrMatch");
                    } else {
                        log("$$StrMatch");
                    }
                    // We substring from 3 to len - 1 to strip off the
                    // non-capture group syntax added as a WebKit workaround
                    log(match.substring(3, match.length - 1));
                }
                const reg = new RegExp(match, "y");
                reg.lastIndex = this.mark().overallPos;
                const res = reg.exec(this.input);
                if (res) {
                    let lineJmp = 0;
                    let lind = -1;
                    for (let i = 0; i < res[0].length; ++i) {
                        if (res[0][i] === "\n") {
                            ++lineJmp;
                            lind = i;
                        }
                    }
                    this.pos = {
                        overallPos: reg.lastIndex,
                        line: this.pos.line + lineJmp,
                        offset: lind === -1 ? this.pos.offset + res[0].length : (res[0].length - lind - 1)
                    };
                    return res[0];
                }
                return null;
            }, cr)();
    }
    private noConsume<T>(fn: $$RuleType<T>): Nullable<T> {
        const mrk = this.mark();
        const res = fn();
        this.reset(mrk);
        return res;
    }
    private negate<T>(fn: $$RuleType<T>): Nullable<boolean> {
        const mrk = this.mark();
        const oneg = this.negating;
        this.negating = !oneg;
        const res = fn();
        this.negating = oneg;
        this.reset(mrk);
        return res === null ? true : null;
    }
}
export function parse(s: string): ParseResult {
    const p = new Parser(s);
    return p.parse();
}
export class ParseResult {
    public ast: Nullable<ROOT>;
    public err: Nullable<SyntaxErr>;
    constructor(ast: Nullable<ROOT>, err: Nullable<SyntaxErr>) {
        this.ast = ast;
        this.err = err;
    }
}
export interface PosInfo {
    readonly overallPos: number;
    readonly line: number;
    readonly offset: number;
}
export class SyntaxErr {
    public pos: PosInfo;
    public exprules: string[];
    public expmatches: string[];
    constructor(pos: PosInfo, exprules: Set<string>, expmatches: Set<string>) {
        this.pos = pos;
        this.exprules = [...exprules];
        this.expmatches = [...expmatches];
    }
    public toString(): string {
        return `Syntax Error at line ${this.pos.line}:${this.pos.offset}. Tried to match rules ${this.exprules.join(", ")}. Expected one of ${this.expmatches.map((x) => ` '${x}'`)}`;
    }
}
class ErrorTracker implements ContextRecorder {
    private mxpos: PosInfo = {overallPos: -1, line: -1, offset: -1};
    private mnd: number = -1;
    private prules: Set<string> = new Set();
    private pmatches: Set<string> = new Set();
    public record(pos: PosInfo, depth: number, result: any, negating: boolean, extraInfo: string[]) {
        if ((result === null) === negating) {
            return;
        }
        if (pos.overallPos > this.mxpos.overallPos) {
            this.mxpos = pos;
            this.mnd = depth;
            this.pmatches.clear();
            this.prules.clear();
        } else if (pos.overallPos === this.mxpos.overallPos && depth < this.mnd) {
            this.mnd = depth;
            this.prules.clear();
        }
        if (this.mxpos.overallPos === pos.overallPos && extraInfo.length >= 2) {
            if (extraInfo[0] === "$$StrMatch") {
                this.pmatches.add(extraInfo[1]);
            }
            if (extraInfo[0] === "$$!StrMatch") {
                this.pmatches.add(`not ${extraInfo[1]}`);
            }
        }
        if (this.mxpos.overallPos === pos.overallPos && this.mnd === depth) {
            extraInfo.forEach((x) => { if (x !== "$$StrMatch" && x !== "$$!StrMatch") { this.prules.add(x); } });
        }
    }
    public getErr(): SyntaxErr | null {
        if (this.mxpos.overallPos !== -1) {
            return new SyntaxErr(this.mxpos, this.prules, this.pmatches);
        }
        return null;
    }
}